FROM golang:1.14.3-alpine

ENV PROJECTROOT=/go/src/github.com/biwow/ChainServer

COPY . $PROJECTROOT/

RUN cd $PROJECTROOT/ && go build -o ChainServer

FROM alpine

ENV PROJECTROOT=/go/src/github.com/biwow/ChainServer

# 原有的dockerfile内容不变，新增下面一行
RUN echo -n 'VFppZjIAAAAAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAAAAAAaAAAAAgAAAAjIWV6AyQn5cMnTvQDLBYrwy3xAANI7PvDTi3uA1EKt8NVFIgDWTL/w1zy/ANgGZnDZHfKA2UF88B66UiAfaZuQIH6EoCFJfZAiZ6EgIylfkCRHgyAlEnwQJidlICbyXhAoB0cgKNJAEAABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAB+kAEAAABwgAAEQ0RUAENTVAAAAAAAVFppZjIAAAAAAAAAAAAAAAAAAAAAAAADAAAAAwAAAAAAAAAbAAAAAwAAAAz/////fjZDKf/////IWV6A/////8kJ+XD/////ydO9AP/////LBYrw/////8t8QAD/////0js+8P/////Ti3uA/////9RCrfD/////1UUiAP/////WTL/w/////9c8vwD/////2AZmcP/////ZHfKA/////9lBfPAAAAAAHrpSIAAAAAAfaZuQAAAAACB+hKAAAAAAIUl9kAAAAAAiZ6EgAAAAACMpX5AAAAAAJEeDIAAAAAAlEnwQAAAAACYnZSAAAAAAJvJeEAAAAAAoB0cgAAAAACjSQBACAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIAAHHXAAAAAH6QAQQAAHCAAAhMTVQAQ0RUAENTVAAAAAAAAAAKQ1NULTgK'|base64 -d > /etc/localtime && echo -n 'Asia/Shanghai' > /etc/timezone

COPY --from=0  $PROJECTROOT/ChainServer /usr/bin
WORKDIR /data

CMD ["ChainServer"]
